 # Tasks file for the role user-n01728463
- name: Create Groups
  group:
    name: "{{ group }}"
    state: present

- name: Create users and added them to the groups
  user:
    name: "{{ item }}"
    groups: "{{ group }},wheel"
    append: yes
    shell: /bin/bash
    state: present
  loop: "{{ users }}"

- name: Create .ssh directory for each user
  file:
    path: "/home/{{ item }}/.ssh"
    state: directory
    mode: '0700'
    owner: "{{ item }}"
    group: "{{ item }}"
  loop: "{{ users }}"

- name: Generate SSH key pair for each user
  openssh_keypair:
    path: "/home/{{ item }}/.ssh/id_rsa"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: '0600'
    type: rsa
    size: 2048
    force: no
  loop: "{{ users }}"

- name: Ensure authorized_keys contains the public key
  copy:
    src: "/home/{{ item }}/.ssh/id_rsa.pub"
    dest: "/home/{{ item }}/.ssh/authorized_keys"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: '0600'
    remote_src: yes
  loop: "{{ users }}"
  
  
- name: Download user100's private SSH key from VM1 to local machine
  ansible.builtin.fetch:
    src: "/home/user100/.ssh/id_rsa"
    dest: "./user100_id_rsa"
    flat: yes
  when: ansible_hostname == "ansible-c-vm1.canadacentral.cloudapp.azure.com"
