---
- name: Install Apache
  package:
    name: "{{ apache_service }}"
    state: present

- name: Create index.html with FQDN
  copy:
    content: "{{ item.fqdn }}"
    dest: "/var/www/html/index.html"
    mode: '0444'
  with_items: "{{ fqdn_file_map }}"
  when: inventory_hostname in item.fqdn

- name: Enable and start Apache
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes

